### ISSUE TITLE
Update Qemu

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/continuous-integration#102]
Qemu 3.1 was released the other week. Debian have updated their packaged version (yay, thank you Michael Tokarev and Debian developers!)

https://tracker.debian.org/news/1010830/accepted-qemu-131dfsg-1-source-into-unstable/

We could update to this. Options are:

 - Do a build of the 3.1 package in an Ubuntu PPA
 - Add Debian unstable as a pinned repository, and install only Qemu
 - Switch (back) to Debian once it hits testing
 - Wait until it appears in Ubuntu (aka do nothing for now)

**Comment by nathanchance** [comment]
Maybe do a 3.1 build with the PPA for early soak testing then switch back to Debian when it's available there?

**Comment by dileks** [comment]
On Sat, Dec 15, 2018 at 4:55 PM Nathan Chancellor <notifications@github.com>
wrote:

> Maybe do a 3.1 build with the PPA for early soak testing then switch back
> to Debian when it's available there?
>
>
Just FYI:

With today's updates I got QEMU 3.1.0 here on Debian/testing AMD64.

# qemu-system-x86_64 --version
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-2)
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers

- Sedat -

>

**Comment by tapaswenipathak** [comment]
Hi @shenki, are you still working on it?

**Comment by tapaswenipathak** [comment]
That's great, I was reading the tickets to see if can help with anything. Let me know if you want to pass this to me.

**Comment by nathanchance** [comment]
I've tested QEMU 3.1 with arm32 (v7), arm64, and x86_64 locally (I got the update on Arch Linux a few weeks ago) with the same parameters we use for CI and had no issues.

**Comment by jorgbrown** [comment]
> I've tested QEMU 3.1 with arm32 (v7), arm64, and x86_64 locally
> (I got the update on Arch Linux a few weeks ago) with the same
> parameters we use for CI and had no issues.

Is anyone testing with riscv?  (And if so, which riscv variant are you using?)

**Comment by groeck** [comment]
I am testing riscv, but with a non-upstream version of qemu for riscv (the upstream version requires the bootloader/rommon to be bundled with the Linux kernel).

**Comment by tapaswenipathak** [comment]
This seems to be all taken per the configs still let me know if you need extra hands. I can see the upstream version of qemu for ppc.

**Comment by shenki** [comment]
Here's a build of Debian's Qemu 3.1 package for Ubuntu Bionic:

 https://launchpad.net/~shenki/+archive/ubuntu/ppa/+build/16258293

If it succeeds we can regenerate the Docker image which will automatically pull in the newer version.

**Comment by nathanchance** [comment]
I pulled down our Docker image, ran `apt-get update && apt-get upgrade`, then ran `./driver.sh`, and it worked fine.

We can manually refresh the image via Travis or just let the cron handle it later today.

**Comment by nathanchance** [comment]
3.1 is now in our latest image: https://travis-ci.com/ClangBuiltLinux/dockerimage/builds/96993872

@shenki did you have any other items you wanted to address with this issue or can it be closed?

**Comment by shenki** [comment]
Great! All done here I think

**Comment by dileks** [comment]
@shenki 
> We could update to this. Options are:
>
>    Do a build of the 3.1 package in an Ubuntu PPA
>    Add Debian unstable as a pinned repository, and install only Qemu
>    Switch (back) to Debian once it hits testing
>    Wait until it appears in Ubuntu (aka do nothing for now)

As QEMU in Debian/testing is version 3.1.0.
Do we switch back to a Debian environment as a base?

[1] https://packages.debian.org/search?suite=buster&keywords=qemu

**Comment by nathanchance** [comment]
I can look into switching us back to Buster Monday afternoon.

**Comment by nathanchance** [comment]
I replied in my head but not here :)

I think we should wait for Buster to hit stable to avoid any weird dependency issues with the LLVM repos because there is only stable and unstable versions. Cosmic is working fine for now.
