### ISSUE TITLE
arm32_v7 linux-next 20190116 regression

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#115]
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/170724607#L6634

https://lore.kernel.org/linux-block/CAJKOXPdQaxKH3z3yMBggP3dAFJ3ecgCcHk=bGaVHZ-Q+V2Riug@mail.gmail.com/

I'll keep an eye on the block mailing list, I assume this will be fixed rather quickly.

**Comment by nickdesaulniers** [comment]
looks like the bisection was found: https://lore.kernel.org/linux-block/CAJKOXPd2WiMC8uc1YuyR+_vEScSewMzQe1Y7UGHgxvkCD+tQ7A@mail.gmail.com/

**Comment by nathanchance** [comment]
Ming posted a patch, which I tested locally: https://lore.kernel.org/linux-block/20190117102657.GB20220@ming.t460p/

Looks like Jens dropped the series from next for the time being so this is no longer an issue.
