### ISSUE TITLE
Wrong flag in Makefile patch

### ISSUE THREAD

**Issue by groeck** [ClangBuiltLinux/continuous-integration#118]
https://github.com/ClangBuiltLinux/continuous-integration/blob/a99c66f52bc56e89eae4b691c783f5f71b96d150/patches/4.19/x86_64/0001-DO-NOT-UPSTREAM-x86-Avoid-warnings-errors-due-to-lac.patch#L29

This is wrong; the conditional must be moved to outside the checkbin: target.

**Comment by groeck** [comment]
Details: With the current head, I get:

make CC=clang-5.0 -j30
scripts/kconfig/conf  --syncconfig Kconfig
arch/x86/Makefile:297: *** recipe commences before first target.  Stop.
when trying to compile.

**Comment by nathanchance** [comment]
Does the change I made in #119 fix it?

**Comment by groeck** [comment]
yes, as mentioned in the pull request.
