### ISSUE TITLE
x86_64 patch application fails on next-20190301

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#123]
Commit [2a418cf3f5f1](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=2a418cf3f5f1caf911af288e978d61c9844b0695) ("x86/uaccess: Don't leak the AC flag into __put_user() value evaluation") introduces a conflict in our revert patch. I've fixed this ["locally"](https://github.com/nathanchance/patches/commit/f92a7026b8b789b49110e812bf93e9db30033189) but that commit is in the `x86/urgent` branch so it will likely hit mainline in the next couple of days so I'll refresh the patch for both repos in one pull request (given that linux-next for x86 hasn't been passing for a few weeks now due to https://github.com/ClangBuiltLinux/linux/issues/347).

This issue is mainly just an FYI/reminder for myself.

**Comment by nickdesaulniers** [comment]
blocking testing of https://github.com/ClangBuiltLinux/continuous-integration/pull/124/files. Not urgent, just stating observation.
