### ISSUE TITLE
rebase x86 mainline patches

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#129]
last night's build failed for x86 mainline when trying to apply patches.  They need a rebase. cc @nathanchance

**Comment by nathanchance** [comment]
Thanks, on it. I'll add your patch to the stack as well so we can get some positive results :P

**Comment by nickdesaulniers** [comment]
I've never seen so much green in the whole galaxy! ⭐️ ⚠️
