### ISSUE TITLE
apt.llvm.org builds haven't been updated since February 28th

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#132]
cc @sylvestre (if you'd prefer an LLVM bug, let me know)

**Comment by tpimh** [comment]
Some ubuntu builds are fine: Bionic (18.04) – 13 Mar, Cosmic (18.10) – 12 Mar.

**Comment by sylvestre** [comment]
I was on holidays, i fixed some issues but some others are still there

**Comment by nickdesaulniers** [comment]
@nathanchance would it be helpful to add logic to the script to fail the build if the clang timestamp is greater than a few days from the day of the build?  (That's probably not great for someone using clang-8 or clang-7 for example).

**Comment by nathanchance** [comment]
Sure, I can look into what that would take tonight.

**Comment by tapaswenipathak** [comment]
Hi @nathanchance, If you aren't looking into this, can I take this? I will pr right now.

**Comment by nathanchance** [comment]
Sorry that I didn't post here, I pushed a solution to our Docker image repo as I do not believe this check should be in driver.sh: https://github.com/ClangBuiltLinux/dockerimage/pull/23

**Comment by sylvestre** [comment]
Why is it a big deal when clang hasn't been updated for a few days?

**Comment by nathanchance** [comment]
I wouldn't call it a big deal (the amount of time is arbitrary so I can increase it to whatever we all agree on) and I don't want to make it feel like we are a burden on you but we are running continuous integration with these builds and we want to catch issues like #416 as quickly as possible.

**Comment by nickdesaulniers** [comment]
@sylvestre is the update process for binaries on apt.llvm.org automated or manual?

**Comment by sylvestre** [comment]
@nickdesaulniers This is fully automated but ... as I use different (and old) versions of Ubuntu and Debian, it requires some hacking from time to time (old gcc, old version of sphinx, bugs in binutils, etc).

Also, new files are added all the times, so, I need to refresh the file list (but this is easy) + rebase of the patches.

So, it requires time and I didn't had some lately to take care of the various regressions

**Comment by nickdesaulniers** [comment]
good to know; thanks for all of the work you do.  It's critical for us and our efforts and we appreciate it!

**Comment by sylvestre** [comment]
Happy to have users like you folks!

Btw, if you use Debian testing or the latest Ubuntu, it should be updated more often (less regressions)

**Comment by sylvestre** [comment]
I don't know which version of Ubuntu you use but I think I fixed trusty (cmake 3.4.3 was buggy)
We should know more tomorrow!

**Comment by sylvestre** [comment]
Yeah, snapshot should be updated on all supported platforms
7 and 8 will follow up later (it takes between 4 to 6 hours per arch)

**Comment by tpimh** [comment]
@sylvestre Looks like the builds are not being updated again. Can you take a look please?
