### ISSUE TITLE
QEMU doesn't exit cleanly for PowerPC on Debian

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#137]
After switching us back to a Debian base in #135, the PowerPC builds do not exit cleanly. Reverting back to Ubuntu fixes this (which would be @shenki's package).

This doesn't appear to be Clang related as reverting back to `clang-8` doesn't change anything and I can't reproduce locally on my server, which is running Arch Linux and using QEMU 3.1 as well.

**Comment by shenki** [comment]
Do you have a log?

**Comment by nathanchance** [comment]
It just hangs until `timeout` kills it (exit code 124); sorry, should have been clearer.

**Comment by shenki** [comment]
Any chance of a log so I can see where it gets to before hanging?

**Comment by nathanchance** [comment]
Yup: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/185056479

**Comment by shenki** [comment]
Thanks. It's hanging when performing the shutdown:

```
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system poweroff
[   21.196172] spin_lock-torture: Unscheduled system shutdown detected
[   21.206716] reboot: Power down
[   22.110546048,5] OPAL: Shutdown request type 0x0...
```
The shutdown request (IPMI message) doesn't take affect. This happens with a GCC built 4.19.13, so it's nothing to do with clang.

The version of skiboot, the powernv firmware, is v6.2. If I locally build skiboot 6.2 it fails. With skiboot master (v6.2-64-gccfd3547af37) it works. I did a scan of the 64 commits, and this one looked suspicious: https://github.com/open-power/skiboot/commit/44aa41061a9ffc289ff6b7d7b47132c4f15896bd. Sure enough, reverting that causes qemu to hang again.

We need to get that patch applied to the Debian skiboot build.

**Comment by shenki** [comment]
I put together a fix where we include a newer skiboot along side the other ppc64le images:

 https://github.com/ClangBuiltLinux/continuous-integration/pull/138

I've also emailed the Debian maintainer to see if they can update the package. The latest skiboot-6.2.x release (6.2.2) includes the patch.

**Comment by dileks** [comment]
Thanks @shenki
