### ISSUE TITLE
Travis Job #694.6

### ISSUE THREAD

**Issue by phongt** [ClangBuiltLinux/continuous-integration#156]
**[Error log]**

https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/196395823#L779

**[Analysis outcome]**
using not suitable macro be32_to_cpu()

**[patch submit to kernel mailing list]**
[of: replace be32_to_cpu to be32_to_cpup](https://marc.info/?l=linux-kernel&m=155661498721783&w=2)

**Comment by nathanchance** [comment]
I think that this is better tracked at https://github.com/ClangBuiltLinux/linux/issues/460, feel free to reopen if you feel differently.

**Comment by nickdesaulniers** [comment]
thanks for taking the time to report the build breakage.  I think it would be even better in the future to file new bugs per warning/error if there's not already one that exists in [the issue tracker](https://github.com/ClangBuiltLinux/linux/issues).
