### ISSUE TITLE
Recent failures after turning on more LLVM tools

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#164]
* https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950114
  https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950118
  https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950120

  Stuff along the lines of:

  ```
  0000000000000000 R_AARCH64_ABS64 sort
  0000000000000008 R_AARCH64_ABS64 __ksymtab_strings
  drivers/firmware/efi/libstub/lib-sort.stub.o: absolute symbol references not allowed in the EFI stub
  ```

  It looks like this is probably caused by `llvm-strip` not supporting the globs in `STUBCOPY_RM-y`, which @rupprecht noted [here](https://github.com/ClangBuiltLinux/linux/issues/435#issuecomment-477387356). These were removed upstream in https://github.com/torvalds/linux/commit/02562d0ca1084a688ac5c92e0e92947f62f13093 because of https://github.com/torvalds/linux/commit/f922c4abdf7648523589abee9460c87f51630d2f. https://github.com/torvalds/linux/commit/f922c4abdf7648523589abee9460c87f51630d2f decently backports to 4.9 and 4.14, not so clean for 4.4. Might be wise to conditionally turn on `llvm-strip`.

* https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950119
  https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950121

  ```
  llvm-objcopy-9: error: 'firmware/e100/d101m_ucode.bin.ihex': The file was not recognized as a valid object file
  ```

  Relevant bits of Makefile:

  ```
  fw-shipped-$(CONFIG_E100) += e100/d101m_ucode.bin e100/d101s_ucode.bin \
			     e100/d102e_ucode.bin
  ...
  quiet_cmd_ihex  = IHEX    $@
      cmd_ihex  = $(OBJCOPY) -Iihex -Obinary $< $@
  ```

  This was "resolved" upstream by https://github.com/torvalds/linux/commit/5620a0d1aacd554ebebcff373e31107bb1ef7769, which we obviously can't backport. We could apply a local patch that removes the `fw-shipped` rule in the Makefile or fix `llvm-objcopy` (if it is even broken).

**Comment by nickdesaulniers** [comment]
that's ok, the failures were intentional to shake up bugs.  Let's:
1. File relevant bugs per issue to track getting these turned back on.
2. revert my enabling of strip and objcopy
3. fix bugs from 1
4. revert the revert from 2
Sound good?

**Comment by nathanchance** [comment]
Sounds good to me!

**Comment by rupprecht** [comment]
For the glob characters issue, it sound like there's no opposition to just supporting them: https://bugs.llvm.org/show_bug.cgi?id=41268. No one has gotten around to it yet.

ihex support is coming in D60270, but I haven't had any time in the past few weeks to review it.

**Comment by nathanchance** [comment]
We are tracking this in https://github.com/ClangBuiltLinux/linux/issues/478 and https://github.com/ClangBuiltLinux/linux/issues/480, I don't think there is any reason to keep this open.
