### ISSUE TITLE
LLVM_VERSION=8 builds after asm goto

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#167]
This is a meta issue to decide what to do about the LLVM 8 builds we are running once asm goto is available to us in an LLVM 9 build. Do we keep the asm goto removal patches around for just LLVM 8 or do we turn off LLVM 8 builds until LLVM 9 is stable, where we would make LLVM 9 builds the stable ones and LLVM 10 the development ones?

**Comment by nickdesaulniers** [comment]
implications for https://github.com/ClangBuiltLinux/continuous-integration/commits/asm_goto.  Let me think more about this.  @arndb has a crazy idea to do our own release of clang-8 for kernel.org, with asm goto fully backported.  I like that idea.

**Comment by nathanchance** [comment]
![he's a madman](https://www.reactiongifs.us/wp-content/uploads/2013/08/hes_a_madman_futurama.gif "He's a madman!")

I like the idea too, especially since it would tackle getting clang builds available for everyone which was mentioned back at Linux Plumbers.
