### ISSUE TITLE
improve ccache hit rate to speed up tests

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#20]
From: https://nickdesaulniers.github.io/blog/2018/06/02/speeding-up-linux-kernel-builds-with-ccache/ we should investigate ripping out the date string.  I think this may be tricky to test entirely before landing something: it will only improve the build time once the cache is hot.

**Comment by nathanchance** [comment]
A simple `git commit --amend` + force push should trigger another build. I'm planning another pull after your lld one, I can see if this works.

**Comment by nickdesaulniers** [comment]
oh, right. I think travis has UI for rekicking the build, too.

**Comment by nathanchance** [comment]
Something else coming into play could be different user/host values given that we get a new set of those each build. I'm going to set `KBUILD_BUILD_USER` and `KBUILD_BUILD_HOST` in addition to `KBUILD_BUILD_TIMESTAMP`. Maybe `driver@clangbuiltlinux` or something?

**Comment by nickdesaulniers** [comment]
build [142](https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/90177202) may have just poisoned the cache from build [141](https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/90177085); you might have to rekick the PR/branch without any builds inbetween (like the daily cron job) to see any benefit.  If you can do, a link to the sped up build would be nice to have, in case the cache gets poisoned again after it's ready to be merged.

**Comment by nathanchance** [comment]
Yeah I'll make sure that there are back to back builds with nothing in between.

**Comment by nathanchance** [comment]
arm and x86_64 had short build times but arm64 didn't, making me think that `CONFIG_LOCALVERSION_AUTO` needs to go too.

**Comment by nickdesaulniers** [comment]
That something is different for one arch makes me think that's an upstream
bug that possibly could be fixed.

**Comment by nathanchance** [comment]
Hmmm not sure I follow but maybe? We'll see how 331ce55d0731ef1c51a83aa947d8697104924e33 does

**Comment by nathanchance** [comment]
Hmmm arm32 and x86_64 still see huge gains with the latest commits but arm64 doesn't... https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/90180531

What's bizarre is locally the speed up is noticeable. I guess it has to be something with the environment because that's the only thing that is different :/

Still worth shipping I think.

**Comment by nickdesaulniers** [comment]
sure, ship it and file a new issue to follow up on arm64. some is better than none.
