### ISSUE TITLE
ccache misbehavior

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#23]
followup from #22 .

ccache has been misbehaving:
- hard to tell if other branch builds are related or not
- increase cache size
- arm64 seems to have issues with ccache, but reportedly not locally, only remote on travis.

[travis ci ccache docs](https://docs.travis-ci.com/user/caching/)

**Comment by tpimh** [comment]
Why are we building ccache from source? Why not just install it from official Ubuntu repos or PPA? Is there any particular reason for this?

**Comment by nathanchance** [comment]
3.1.9 (Trusty's version) has a bug where a ton of warnings were emitted, which was fixed in 3.2:

"ccache no longer passes preprocessor options like -D and -I to the compiler when compiling preprocessed output. This fixes warnings emitted by Clang.".

It takes us literally five seconds to fetch and build ccache, it's like 10 files big. I don't use Ubuntu so

**Comment by tpimh** [comment]
Thanks for your explanation. Maybe you could consider using [this PPA](https://launchpad.net/~clearpath-robotics/+archive/ubuntu/ccache). But since it's just a matter of 5 seconds, it's not that important.

**Comment by nickdesaulniers** [comment]
If we move to docker in #25 , is it possible to move the ccache dir to [a dir that travis itself caches](https://docs.travis-ci.com/user/caching#arbitrary-directories)? (Doesn't need to be in #25 )

**Comment by nathanchance** [comment]
Yes we could. I already have to make adjustments to the PR so I might as well do it at the same time.

**Comment by nathanchance** [comment]
Alright seems like it is working a little better now: https://travis-ci.com/nathanchance/continuous-integration/builds/90440872

I'll push to the PR here shortly once I clean up my testing.

**Comment by nickdesaulniers** [comment]
Hey that's great! Looks like no spooky 👻 bugs with arm64 builds we were seeing before!

**Comment by nickdesaulniers** [comment]
Fixes in #25 , thanks @nathanchance !  Next build (163) of master should have a cold cache, but subsequent builds should have a nice hot cache.
