### ISSUE TITLE
make -s

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#230]
suggested by @arndb

**Comment by nickdesaulniers** [comment]
what was the argument again for why we didn't like `-s` @tpimh @nathanchance ?

**Comment by nathanchance** [comment]
Travis times out if it has not seen any input within 10 minutes: https://travis-ci.com/github/nathanchance/continuous-integration/jobs/285085564

**Comment by nickdesaulniers** [comment]
ah, so an issue specific to travis; thanks for the link!
