### ISSUE TITLE
additional info that may be useful to log

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#26]
We already print kernel version string which has the clang latest svn commit number, and log each command (`set -x`).

Thoughts:
* Latest linux kernel commit (`git show -1 | cat`)
* Time build took (`time make -j ...`)
* ccache stats before and after (`ccache -s`)
* ???

**Comment by nickdesaulniers** [comment]
ccache stats were added in #25

**Comment by nathanchance** [comment]
`time` and `git show -1 | cat` would be good addition. I cannot personally think of any other good information off the top of my head.
