### ISSUE TITLE
change `AS=clang` to `LLVM_IA=1` for -next

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#260]
via: https://lore.kernel.org/lkml/20200407184336.14612-2-masahiroy@kernel.org/T/#m9108dccbbd93f16c418c6e90e01a85262b81ce89

when this lands, we'll need to change `AS=clang` to `LLVM_IA=1` for -next. (cc @nathanchance @masahir0y )

**Comment by nathanchance** [comment]
Done in #262, forgot to put the “closes” tag.

**Comment by masahir0y** [comment]
Please change it to LLVM_IAS=1, not LLVM_IA=1.

This is the picked version:
https://patchwork.kernel.org/patch/11479149/

Fangrui Song mentioned 'IAS' is a more common abbreviation.
