### ISSUE TITLE
powerpc64{,le} boot failures after next-20200402

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration#262]
Starting with `next-20200402`, powerpc64 (`pseries_defconfig`) and powerpc64le (`powernv_defconfig`) fail to boot when [the torture tests](https://github.com/ClangBuiltLinux/continuous-integration/blob/09d8e9d8a85d0825fa9d8e48537f68c77cab2a8c/configs/tt.config) are enabled. I could not reliably reproduce it in my local environment but I could with our Docker image. I initially bisected this down to commit [3282a3da25bd](https://git.kernel.org/linus/3282a3da25bd63fdb7240bc35dbdefa4b1947005) ("powerpc/64: Implement soft interrupt replay in C") in Linux.

However, I realized that my host's QEMU version was 4.2.0 (latest stable), whereas the one in our Docker image is 3.1.0 (Debian stable). I bisected the failures separately because I wasn't getting consistent results when doing it together. They converged on commits that did similar things though. `powernv_defconfig` was resolved by https://github.com/qemu/qemu/commit/f30c843ced5055fde71d28d10beb15af97fdfe39 and `pseries_defconfig` was resolved by https://github.com/qemu/qemu/commit/34a6b015a98733a4b32881777dafd70156c5a322.

To show this is not just a fluke, I built a kernel for each config and booted it 100 times in QEMU, logging the result. 3.1.0 fails approximately 80% of the time but 4.2.0 and 5.0.0-rc2 failed only 1% of the time. I did the same thing with kernels built with GCC 9.3.0 and saw similar rates of failure.

Clang:

![image](https://user-images.githubusercontent.com/11478138/78957618-b1842080-7a9a-11ea-8856-279c3dcc6c19.png)

GCC:

![image](https://user-images.githubusercontent.com/11478138/78955535-62d38800-7a94-11ea-9e61-9e3d8c068ace.png)

I have not looked into why the Linux commit causes 3.1.0 to fail as much as it did but without access to actual hardware, I am not confident in saying this is a bug in Clang or Linux or even bothering the PowerPC guys upstream.

To get QEMU 4.2.0, we would need to update our Docker image to Debian unstable, which is what I would recommend doing. My smoke tests have shown no regressions.

cc @daxtens @shenki just in case you guys have any comments/thoughts.

**Comment by nickdesaulniers** [comment]
Great visualizations! Let's upgrade our QEMU then.

**Comment by nathanchance** [comment]
Great. I will test a new Docker image locally then push it for review.

**Comment by nickdesaulniers** [comment]
It might still be worthwhile to post on the ppc mailing list so there's more records of this, for future travelers.

Also, it might be worthwhile to push your script to github, should we need it again.  We can always adapt it in the future if needed.

**Comment by nathanchance** [comment]
> It might still be worthwhile to post on the ppc mailing list so there's more records of this, for future travelers.

Ack, I'll draft something up.

> Also, it might be worthwhile to push your script to github, should we need it again. We can always adapt it in the future if needed.

Already have, just a private gist: https://gist.github.com/nathanchance/f9ce5f6fd06d218269cfca6564d60a0c

Should be fairly readable. Needs three folders where it is with QEMU 3.1.0, QEMU 4.2.0, and QEMU 5.0.0-rc2 in it, it's easy to build.

**Comment by nathanchance** [comment]
Posted: https://lore.kernel.org/linuxppc-dev/20200410205932.GA880@ubuntu-s3-xlarge-x86/

**Comment by nathanchance** [comment]
Summary of discussion upstream is that it is a QEMU bug and it is merely coincidence that it was fixed (bump from power8 to power9). If it regresses again, we might need to turn off the torture tests but for now, I'm closing this up.
