### ISSUE TITLE
numerous aarch64 failures

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#284]
not sure if these are all timeouts, but a lot of aarch64 builds are failing
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/builds/171997538

**Comment by nickdesaulniers** [comment]
no longer reproducible?

**Comment by nathanchance** [comment]
We increased the timeout to 8m in #312 so this should be resolved for now.
