### ISSUE TITLE
builds disabled

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#334]
There's a banner now above our CI page:

Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

**Comment by nathanchance** [comment]
I guess we will need to reach out to Travis and request some OSS credits: https://docs.travis-ci.com/user/billing-overview

Otherwise, we will need to look at migrating to something else, maybe GitHub Actions?

**Comment by nickdesaulniers** [comment]
We received an email yesterday that we were granted OSS credits.  The build ran last night. I think I'd rather turn these off.

**Comment by nathanchance** [comment]
I went ahead and suspended Travis's access to our repos.
