### ISSUE TITLE
Package skiboot.lid for qemu

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/continuous-integration#38]
Upstream Qemu bundles skiboot but Debian strips all binaries out when packaging.

Debian already packages some of the tools that live in the skiboot repo, but doesn't ship the actual firmware.

I've done some work to package skiboot.lid so we can install it through apt in the same way that qemu pulls in the firmware for the x86 machine (seabios, ipxe-qemu, etc). The idea would be we get Debian to include that package and it all "just works" in the future.

The wip is in my PPA: https://launchpad.net/~shenki/+archive/ubuntu/ppa/+packages

**Comment by nickdesaulniers** [comment]
more info for future travelers: https://github.com/ClangBuiltLinux/continuous-integration/pull/37#issuecomment-437356590 :alien: :space_invader: :artificial_satellite:

**Comment by shenki** [comment]
Debian has accepted these changes into the skiboot packaging as of 6.1-3. The `qemu-skiboot` package can be installed in Debian testing and Ubuntu Disco.

**Comment by tpimh** [comment]
Should this be reopened, because even though the `qemu-skiboot` package is in Debian repo and even included in the Docker image, it's not being used?
