### ISSUE TITLE
make local development friendlier

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#4]
currently we always wipe away existing binaries.  Maybe a flag to say do/don't wipe, or poor man's caching by comparing sha1sums of binaries written out?

**Comment by nathanchance** [comment]
I will add a `-c`/`--clean` parameter that will clean up old artifacts. Given that both LLVM and Linux's build systems are good at figuring out what needs to be built, we shouldn't need to use that often. Can also use ccache as well if we wanted some speed up.

**Comment by tpimh** [comment]
@nathanchance Maybe we can set ccache directory to a remote persistent storage so it will work well in travis across builds? Never seen this actually implemented, but should be doable.
