### ISSUE TITLE
investigate caching linux source dir

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#68]
We already restore the ccache dir, I wonder if we can do so with the linux source dir. Then we can `git fetch <remote>/<branch>` then `git reset --hard FETCH_HEAD`.  Might not actually be worth it if we can shallow clone faster.  We could probably compress/decompress the source dir though.  Not a high priority.

**Comment by tapaswenipathak** [comment]
Hi @nickdesaulniers, I'm curious if there is something different happening in these [lines](https://github.com/ClangBuiltLinux/continuous-integration/blob/552733f7f05ba8d074e4c9edbf59cdf328dd0ad0/driver.sh#L230-L245)? According to my reading I think this is already done. Would something like [this](https://github.com/ClangBuiltLinux/continuous-integration/pull/144) be useful? Another point there is something as `before_cache` in Travis where the installation speed could be increased further.

**Comment by nathanchance** [comment]
What Nick is suggesting is adding the kernel repos to the cache section in `.travis.yml`, not caching/decompressing the continuous integration repo.

I personally do not think this is worth doing, shallow clones are quick and Travis still has to download the cached files anyways (and we'd still need to fetch and reset hard, it's not even saving steps).

**Comment by tapaswenipathak** [comment]
I agree on shallow clones. I'm thinking of compressing/decompressing the kernel src code, sorry I should add proper zip command. Should I time this and check? Should I add kernel repos to the cache section? Is there anything open in this ticket then?

**Comment by nathanchance** [comment]
You're welcome to try caching the kernel folder and timing it but I doubt the added complexity is going to be worth it. Otherwise, no, this issue has nothing else to do.

**Comment by tapaswenipathak** [comment]
What is the complexity in adding the linux src dir in cache?

**Comment by tapaswenipathak** [comment]
Yea, this ticket can be closed. The only todo I see is running the Travis w/ enabling kernel src dir in cache w/ compressing/decompressing kernel src dir. I will update.

**Comment by nickdesaulniers** [comment]
That's ok, sometimes research ends up finding out that a hypothesis was not the right direction, even after significant effort was put in.  That doesn't make the effortless worthless.  Thanks for taking the time to investigate. 🌤
