### ISSUE TITLE
auto update repo

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#8]
so the travis stuff only runs when a PR is submitted.  I wonder if there's a clever way to trigger it on some kind of time basis?

**Comment by nathanchance** [comment]
Travis has a cron feature that can run daily, which I set up for the master branch: https://docs.travis-ci.com/user/cron-jobs/

I'll need to update the script to fetch the latest revision before building if we go that route:

```
git fetch --depth=1 origin master
git reset --hard origin/master
```

Alternatively, I can set up my cron to auto-update the repo every few hours like I do for the other repositories and that will trigger Travis builds.

**Comment by nickdesaulniers** [comment]
Neat! Thanks! Let's keep the travis setting then.

I think one issue is the git submodules will eventually fail to sync.  Is that what you're referring to?

**Comment by nathanchance** [comment]
I don't know if submodules are limited by Travis' 50 commit checkout limit or whatever but at the very least, without bumping the submodule commit like in d3da99cfb78d5ecd3ff5c78050ad5cc5924d3273 or updating via the script, we'll just be building the same commit over and over.

**Comment by nickdesaulniers** [comment]
See [build 52](https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/89883569) just errored. I think there's an issue with git submodules where people configure their git servers to not allow people to arbitrarily sync X commits back from HEAD.  `git submodule update --init --recursive` also fails for my local checkout...

**Comment by nathanchance** [comment]
Ugh that's annoying... At the very least, we'll need to always update the submodule when making a PR manually then. As for keeping things continuous, that'll require a bit more brainstorming. Only thing that comes to mind is a cron job that does something like this:

```
cd linux
git fetch --depth=1 origin master
git reset --hard origin/master
cd ..
git add linux
git commit -m "linux: Update to <sha>"
git push
git pull-request -b master
```

Last one is a `hub` command but would allow us to keep protected status on master

**Comment by nickdesaulniers** [comment]
Also, seems like you can tell travis to not handle the submodule syncs: https://github.com/algolia/examples/issues/24

but I'll whip up a cl removing the submodule.
