### ISSUE TITLE
kernelci gearing up for clang

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#80]
https://github.com/kernelci/kernelci-core-staging/blob/master/jenkins/dockerfiles/clang-8/Dockerfile :) cc @nathanchance

**Comment by tapaswenipathak** [comment]
Hi @nickdesaulniers, what is this about?

**Comment by tapaswenipathak** [comment]
Better question, I see the Dockefile for clang-8, are you still working on it?

**Comment by nickdesaulniers** [comment]
Just an announcement issue. Closing.
