### ISSUE TITLE
add android common kernels to build targets

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#91]
I think it would be neat to add common kernels.  We support fetching from various tree+branches already, should just be new trees/branches.  Probably simpler to not involve the android binutils and just add the trees for MVP. Thoughts, @ajs1984 ?

**Comment by tapaswenipathak** [comment]
Hi @ajs1984, let me know if you need hands for this? What is its status, are you working on it?
